version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: anti-fraud-db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - anti-fraud-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: anti-fraud-web
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp/pids/
    networks:
      - anti-fraud-network

volumes:
  db-data:

networks:
  anti-fraud-network: